name: Cubit
main : de.linzn.cubit.bukkit.plugin.CubitBukkitPlugin
version: ${project.version}
description: A worldguard region manager for bukkit servers
author: Niklas Linz
load: POSTWORLD
depend: [WorldEdit, WorldGuard, Vault]

commands:
  cubit:
    description: Plugin command
  land:
    description: Land Command
  shop:
    description: Shop Command
    aliases: [shops]
  cadmin:
    description: Admin Command
    aliases: [sadmin, ladmin, shopadmin, landadmin]
permissions:
    cubit.user:
        description: User main permissions
        children:
            cubit.command.user.land: true
            cubit.command.user.shop: true
    cubit.admin:
        description: Admin main permissions
        children:
            cubit.command.admin.land: true
            cubit.bypass.kick: true
            cubit.admin.checkupdate: true
    cubit.command.user.land:
        description:  User command permissions
        children:
            cubit.command.land.info: true
            cubit.command.land.buy: true
            cubit.command.land.sell: true
            cubit.command.land.help: true
            cubit.command.land.addmember: true
            cubit.command.land.removemember: true
            cubit.command.land.offer: true
            cubit.command.land.takeoffer: true
            cubit.command.land.buyup: true
            cubit.command.land.kick: true
            cubit.command.land.list: true
            cubit.command.land.flag.pvp: true
            cubit.command.land.flag.fire: true
            cubit.command.land.flag.lock: true
            cubit.command.land.flag.tnt: true
            cubit.command.land.flag.monster: true
            cubit.command.land.flag.potion: true
            cubit.command.land.changebiome: true
            cubit.command.land.listbiomes: true
            cubit.command.land.restoresnapshot: true
            cubit.command.land.savesnapshot: true
            cubit.command.land.resetsnapshot: true
            cubit.command.land.listsnapshots: true
            cubit.command.land.showmap: true
    cubit.command.user.shop:
        description:  User command permissions
        children:
            cubit.command.shop.buy: true
            cubit.command.shop.sell: true
            cubit.command.shop.info: true
            cubit.command.shop.addmember: true
            cubit.command.shop.removemember: true
            cubit.command.shop.kick: true
            cubit.command.shop.help: true
            cubit.command.shop.list: true
            cubit.command.shop.changebiome: true
            cubit.command.shop.listbiomes: true
    cubit.command.admin.land:
        description: Admin command permissions
        children:
            cubit.command.user.land: true
            cubit.command.user.shop: true
            cubit.command.admin.sell: true
            cubit.command.admin.addmember: true
            cubit.command.admin.removemember: true
            cubit.command.admin.offer: true
            cubit.command.admin.createserver: true
            cubit.command.admin.deleteserver: true
            cubit.command.admin.createshop: true
            cubit.command.admin.deleteshop: true
            cubit.command.admin.list: true
            cubit.command.admin.help: true
            cubit.command.admin.changebiome: true
            cubit.command.admin.listbiomes: true
            cubit.command.admin.flag.pvp: true
            cubit.command.admin.flag.fire: true
            cubit.command.admin.flag.lock: true
            cubit.command.admin.flag.tnt: true
            cubit.command.admin.flag.monster: true
            cubit.command.admin.flag.potion: true
            cubit.command.admin.reloadcubit: true
            cubit.command.admin.listsnapshots: true
    cubit.command.land.info:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.buy:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.sell:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.help:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.addmember:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.removemember:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.offer:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.takeoffer:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.kick:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.list:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.restoresnapshot:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.savesnapshot:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.resetsnapshot:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.listsnapshots:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.changebiome:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.listbiomes:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.buyup:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.showmap:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.flag.pvp:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.flag.fire:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.flag.lock:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.flag.tnt:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.flag.monster:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.land.flag.potion:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.shop.buy:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.shop.sell:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.shop.info:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.shop.list:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.shop.changebiome:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.shop.listbiomes:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.shop.help:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.shop.addmember:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.shop.removemember:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.shop.kick:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.admin.sell:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.admin.addmember:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.admin.removemember:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.admin.offer:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.admin.help:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.admin.list:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.admin.listbiomes:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.admin.listsnapshots:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.admin.changebiome:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.admin.createserver:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.admin.deleteserver:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.admin.createshop:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.admin.deleteshop:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.admin.flag.pvp:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.admin.flag.fire:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.admin.flag.lock:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.admin.flag.tnt:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.admin.flag.monster:
        description: Haupt-Hilfeseite
        default: op
    cubit.command.admin.reloadcubit:
        description: Haupt-Hilfeseite
        default: op
    cubit.bypass.kick:
        description: Haupt-Hilfeseite
        default: op
    cubit.admin.checkupdate:
        description: Haupt-Hilfeseite
        default: op