name: cookieApiLand
main : de.kekshaus.cookieApi.land.Landplugin
version: ${project.version}.b${build.number}
description: Landplugin
author: Kekshaus
load: POSTWORLD
depend: [cookieApiBukkit]

commands:
  land:
    description: Land Command
  shop:
    description: Shop Command
    aliases: [shops]
  ladmin:
    description: Admin Command
    aliases: [sadmin, shopadmin, landadmin]